### ISSUE TITLE
Add citizens to respective vectors in constructors

### ISSUE THREAD

**Issue by u23535793** [COS214-Project-2024/Till-Dev-do-us-Part#28]
Need to add adults to citizens and unemployed vector and minors to minor vector in their respective constructors/ functions using:     
((SocialAffairsDept*)(Gov->getDepartment("SocialAffairs")))->addCitizen(person);
((SocialAffairsDept*)(Gov->getDepartment("SocialAffairs")))->addToUnemployed(person);
((SocialAffairsDept*)(Gov->getDepartment("SocialAffairs")))->addChild(child);

**Comment by k-aff** [comment]
could not complete. scrapped
