### ISSUE TITLE
Update UMLs

### ISSUE THREAD

**Issue by k-aff** [COS214-Project-2024/Till-Dev-do-us-Part#29]
Update class UML with new function names and added functions and/or classes.

**Comment by k-aff** [comment]
Citizen UML up to date with current functions

**Comment by u23535793** [comment]
Economy UML up to date (locally)

**Comment by thendombedzi** [comment]
The Resources class UML is up to date.

**Comment by u23772141** [comment]
Utilities Class diagram updated
